### ISSUE TITLE
Undefined offset: 1 at /var/www/html/apps/nextcloud_announcements/lib/Notification/Notifier.php#82	

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/nextcloud_announcements#14]
Undefined offset: 1 at /var/www/html/apps/nextcloud_announcements/lib/Notification/Notifier.php#82	

cc @nickvergessen

**Comment by LukasReschke** [comment]
Also I only see a notification that says "Nextcloud notification". Shouldn't we show like the title there or so?

**Comment by nickvergessen** [comment]
I guess the offset 1 issues makes the title being unavailable.
