### ISSUE TITLE
[BITV] Make markup accessible

### ISSUE THREAD

**Issue by Pytal** [nextcloud/nextcloud_announcements#247]
![image](https://github.com/nextcloud/nextcloud_announcements/assets/24800714/0e2e9caf-d3f7-401d-8e02-49e7f5c970ac)

**Comment by Pytal** [comment]
Could this app be disabled for a11y audit or is this necessary @AndyScherzinger ?

**Comment by nickvergessen** [comment]
IIRC we spoke recently that we want to deprecate this app.

**Comment by AndyScherzinger** [comment]
> Could this app be disabled for a11y audit or is this necessary @AndyScherzinger ?

Let's disable it for the audit, decision to fully remove it I will take up with management since I can't make that call myself.

**Comment by AndyScherzinger** [comment]
As discussed via chat let's remove it and merge it with the update notification settings UI
