### ISSUE TITLE
NC 11.0.3 announcement app does not translate 'author' string to 'auteur' for Dutch Lanuage

### ISSUE THREAD

**Issue by JK74** [nextcloud/nextcloud_announcements#25]
NC 11.0.3 and Dutch localization. 

the announcement app shows in dutch: " één uur geledendoor {auteur} "
It seems the app does not translate the string 'author' to {auteur} ".

cheers, jeroen

**Comment by nickvergessen** [comment]
Well words that are wrapped with `{` are placeholders and should not be translated.
I fixed the dutch translation.

**Comment by JK74** [comment]
Thnx but should there not be a name listed?

Groeten, Jeroen Kleen

Op 8 mei 2017 13:05 schreef Joas Schilling <notifications@github.com>:

Well words that are wrapped with { are placeholders and should not be translated.
I fixed the dutch translation.
