### ISSUE TITLE
Uses old select2, should use new vue component

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud_announcements#36]
Using the dark theme it becomes pretty clear especially and looks a bit strange:
![nextcloud announcements uses old select2](https://user-images.githubusercontent.com/925062/51316116-0bdb3080-1a54-11e9-8daa-1ca62d337655.png)

@nextcloud/designers this should probably use the new select component at some point?

**Comment by Pytal** [comment]
Superseded by https://github.com/nextcloud/nextcloud_announcements/issues/247
