### ISSUE TITLE
Nextcloud 21.0.1 Function openssl_free_key() is deprecated at /var/www/nextcloud/apps/nextcloud_announcements/lib/Cron/Crawler.php#177

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/nextcloud_announcements#76]
Server Ubuntu 20.0.4
PHP 8.0
Apache2 
MariaDB 10.3.25
```
{"reqId":"sumTIPnz2JqUcba0vEuQ","level":3,"time":"2021-04-13T20:15:06+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":{"Exception":"Error","Message":"Function openssl_free_key() is deprecated at /var/www/nextcloud/apps/nextcloud_announcements/lib/Cron/Crawler.php#177","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/nextcloud_announcements/lib/Cron/Crawler.php","line":177,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/nextcloud_announcements/lib/Cron/Crawler.php","line":79,"function":"loadFeed","class":"OCA\\NextcloudAnnouncements\\Cron\\Crawler","type":"->"},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/Job.php","line":52,"function":"run","class":"OCA\\NextcloudAnnouncements\\Cron\\Crawler","type":"->"},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php","line":59,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":128,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"--","version":"21.0.1.1","id":"607637dcaeed7"}
```

**Comment by ckujau** [comment]
FWIW, `openssl_free_key` appears also in one instance in the [nextcloud/server](https://github.com/nextcloud/server/) project (in [Installer.php](https://github.com/nextcloud/server/blob/master/lib/private/Installer.php#L310)), do we need a separate bug for this?

**Comment by nickvergessen** [comment]
@LukasReschke any recommended replacement?

**Comment by nickvergessen** [comment]
ah okay, sorry it's only the freeing of the key that is unnecessary, the other methods still work fine?

**Comment by andyxheli** [comment]
> ah okay, sorry it's only the freeing of the key that is unnecessary, the other methods still work fine?

When I did the install I wasn't getting any error regarding installer.php and openssl_free_key so maybe nothing needs to be changed there ?

**Comment by ckujau** [comment]
If `openssl_free_key` isn't called at all in `installer.php`, isn't it dead code then (and better removed altogether)? But again, this is pertaining to `nextcloud/server`, not `nextcloud/nextcloud_announcements`, sorry for the noise here.

**Comment by LukasReschke** [comment]
> @LukasReschke any recommended replacement?

As per https://github.com/php/php-src/blob/php-8.0.0/UPGRADING#L414-L416:

```
  . The openssl_x509_free() function is deprecated and no longer has an effect,
    instead the OpenSSLCertificate instance is automatically destroyed if it is no
    longer referenced.
```

Guzzle went with `unset`. https://github.com/guzzle/oauth-subscriber/pull/82/files

I'd instead propose that we do a PHP version check. If we are >= 8 then we don't execute this piece of code. (and in the future we can remove this completely)

**Comment by LukasReschke** [comment]
https://github.com/nextcloud/nextcloud_announcements/pull/77 is actually good :)
