### ISSUE TITLE
Better visibility needed..

### ISSUE THREAD

**Issue by gecegezen** [nextcloud/nextcloud_announcements#88]
### Steps to reproduce
1. --
2. -- 
3. --

### Expected behaviour

This is more likely a feature request. Anouncements should draw more attention. Perhaps, changing app's top bar icon to red and making it pulse distinctively may help people to notice it. 

Lack of sound warnings is a really annoying issue on browsers; people do not notice things while they are working on other tabs or workspaces. I guess this sound notification issue is a more fundamental problem beyond this app. Anyway, a sound warning is sorely needed in browsers. I hoped announcement center could alleviate this need to an extent, if its icons were in an eye-catching color and even animated when an announcement is received. Another suggestion might be, marking Anouncement's notification in a special distinctive colour and put it always on top of the list than other standard message notifications.

### Actual behaviour
No sound warning, not distinguishable from standard notifications, no special priority and color in notifications. 
### Server configuration

**Operating system**:
Centos 7
**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
21.0.4
**Where did you install Nextcloud from:**
GitHub
**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**
X11 / Firefox 92
**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by nickvergessen** [comment]
I guess you are talking about the announcement center app, not the nextcloud-announcements which are published bei Nextcloud itself not a local admin?

**Comment by gecegezen** [comment]
Uh-oh?! How clumsy of me.. :/ Sorry. You are right. You may remove this.
